import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/src/components/Header'
import Hero from '@/src/components/Hero'
import Mcqs_Home from '@/src/components/Mcqs_Home'
import Footer from '@/src/components/Footer'

// import connectMongo from '../utils/connectMongo';
// import Data from '../models/Data';

// import Image from 'next/image'
// import Mcqs_Home2 from '@/src/components/Mcqs_Home2'
// import BreadCrumb from '@/src/components/BreadCrumb'
// import { Mcqs } from '@/src/components/Mcqs'
// import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div> 
          <Header />
          <Hero />
          <Mcqs_Home />
          {/* <Mcqs_Home2 /> */}
          {/* <Mcqs /> */}
          {/* <BreadCrumb /> */}
          <Footer />
        </div>
      </main>
    </>
  )
}



// export const getServerSideProps = async () => {
//   try {
//     console.log('CONNECTING TO MONGO');
//     await connectMongo();
//     console.log('CONNECTED TO MONGO');

//     console.log('FETCHING DOCUMENTS');
//     const data = await Data.find();
//     console.log('FETCHED DOCUMENTS');

//     return {
//       props: {
//         data: JSON.parse(JSON.stringify(data)),
//       },
//     };
//   } catch (error) {
//     console.log(error);
//     return {
//       notFound: true,
//     };
//   }
// };
